### ISSUE TITLE
Race did not appear in event list

### ISSUE THREAD

**Issue by glenne** [crewtimer/crewtimer-fl-connect#1]
For 2024 ACA Nationals, some races didn't show up in FinishLynx.

Example - R355

**Comment by glenpurdy** [comment]
Specifically R337 did not show up in FinishLynx as a single race nor did the paddlers show up in the Flight that 337 & 338 were part of.

**Comment by glenne** [comment]
This was caused by RaceType exclusions intended to exclude RaceType Info.  Some entries from the ACA regatta did not have the RaceType set so it defaulted to Sprint but the logic treated this as an unknown type and rejected it.
