### ISSUE TITLE
Add support for FinishyLynx time trail 

### ISSUE THREAD

**Issue by reverendseverin** [crewtimer/crewtimer-fl-connect#4]
Currently scoreboard only sends \19 for start time. FinishLynx supports time trail which is useful for multiple starts in short span however it uses a different variable. The CrewTimer.lss file does not currently support this different variable.

\1a  Start Time (Time Trial key match only) 
; Finish Time (for Time Trials)
\1a,"finish":"%s"

**Comment by reverendseverin** [comment]
It started working after adjusting finishlynx setting.

**Comment by glenne** [comment]
Is there a specific setting that needs to be added to the docs?
